package ldv.shuuen.bass

import com.un4seen.bass.BASS
import com.un4seen.bass.BASSMIDI

internal actual object BassConstants {
  actual val BASS_OK: Int = BASS.BASS_OK
  actual val BASS_ERROR_INIT: Int = BASS.BASS_ERROR_INIT
  actual val BASS_CONFIG_BUFFER: Int = BASS.BASS_CONFIG_BUFFER
  actual val BASS_CONFIG_UPDATEPERIOD: Int = BASS.BASS_CONFIG_UPDATEPERIOD
  actual val BASS_CONFIG_DEV_BUFFER: Int = BASS.BASS_CONFIG_DEV_BUFFER
  actual val BASS_CONFIG_DEV_PERIOD: Int = BASS.BASS_CONFIG_DEV_PERIOD
  actual val BASS_ATTRIB_BUFFER: Int = BASS.BASS_ATTRIB_BUFFER
  actual val BASS_STREAM_DECODE: Int = BASS.BASS_STREAM_DECODE
  actual val BASS_MIDI_DECAYEND: Int = BASSMIDI.BASS_MIDI_DECAYEND
  actual val BASS_CONFIG_MIDI_VOICES: Int = BASSMIDI.BASS_CONFIG_MIDI_VOICES
  actual val MIDI_EVENT_NOTE: Int = BASSMIDI.MIDI_EVENT_NOTE
  actual val MIDI_EVENT_PROGRAM: Int = BASSMIDI.MIDI_EVENT_PROGRAM
  actual val MIDI_EVENT_BANK: Int = BASSMIDI.MIDI_EVENT_BANK
  actual val MIDI_EVENT_VOLUME: Int = BASSMIDI.MIDI_EVENT_VOLUME
  actual val MIDI_EVENT_NOTESOFF: Int = BASSMIDI.MIDI_EVENT_NOTESOFF
}
